sudo: required

language: python

services:
  - docker

before_install:
  - docker run -ti --name conangcc7 -v ${PWD}:/home/conan/project lasote/conangcc7

script:
  - sudo pip install -U conan
  - cd /home/conan/project
  - mkdir build && cd build
  - conan install .. -s build_type=Release
  - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
  - ninja
  - ./gtest1"
