sudo: required

language: python

services:
  - docker

before_install:
  - docker run -t -d --name conangcc7 -v ${PWD}:/home/conan/project lasote/conangcc7

script:
  - docker exec conangcc7 sudo pip install -U conan
  - docker exec conangcc7 cd /home/conan/project
  - docker exec conangcc7 mkdir build && cd build
  - docker exec conangcc7 conan install .. -s build_type=Release
  - docker exec conangcc7 cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
  - docker exec conangcc7 ninja
  - docker exec conangcc7 ./gtest1

after_script:
  - docker stop conangcc7
  - docker rm conangcc7
